apiVersion: v1
kind: ReplicationController
metadata:
  name: zoonavigator1
spec:
  replicas: 1
  selector:
    app: zoonavigator1
  template:
    metadata:
      labels:
        app: zoonavigator1
    spec:
      containers:
        - name: zoonavigator1
          image: elkozmon/zoonavigator:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: HTTP_PORT
              value: "8000"
            - name: AUTO_CONNECT_CONNECTION_STRING
              value: "zoo1:2181"
