apiVersion: v1
kind: ReplicationController
metadata:
  name: kafdrop
spec:
  replicas: 1
  selector:
    app: kafdrop
  template:
    metadata:
      labels:
        app: kafdrop
    spec:
      containers:
        - name: kafdrop
          image: obsidiandynamics/kafdrop:3.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: ZOOKEEPER_CONNECT
              value: zoo1:2181,zoo2:2181
            - name: KAFKA_BROKERCONNECT
              value: kaf1:29092,kaf2:29093
