apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka1-pv-claim
  labels:
    app: kafka1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka2-pv-claim
  labels:
    app: kafka2
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: local
