apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka1-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/kubernetes/kafka1"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka2-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/kubernetes/kafka2"
